apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: sulbiraj/gitops-argo-app:replaceImgageTag
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
